# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section_id', models.CharField(max_length=10)),
                ('chapter_id', models.CharField(max_length=10)),
                ('page_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('timesinfo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region_id', models.CharField(max_length=10)),
                ('parent_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('region_id', models.CharField(max_length=10)),
                ('section_id', models.CharField(max_length=10)),
                ('chapter_id', models.CharField(max_length=10)),
                ('page_id', models.CharField(max_length=10)),
                ('stat', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('region_id', models.CharField(max_length=10)),
                ('uid', models.CharField(max_length=10)),
            ],
        ),
    ]
